### ISSUE TITLE
DataLab and EagleWings agent are missing.

### ISSUE THREAD

**Issue by bic4907** [phy-q/benchmark#1]
I opt to run sample AIBirds agents with ScienceBirds, but there's something missing files on your repository.

I refer [this section](https://github.com/phy-q/benchmark#51-how-to-run-heuristic-agents) to run sample agent, however there's no `datalab_037_v4_java12.jar` and `eaglewings_037_v3_java12.jar` in your `sciencebirdsagents/HeuristicAgents/` directory.

As my intuition, I ran `data_lab_agent_v5.jar` and `eagle_wings_agent_v6.jar` files with this command, instead, and some error occurred in my console.  
```bash
java -jar data_lab_agent_v5.jar
```
```bash
(base) inchang@inchang-ubuntu:~/Desktop/benchmark/sciencebirdsagents/HeuristicAgents$ java -jar data_lab_agent_v5.jar 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at ab.demo.MainEntry.main(MainEntry.java:27)
```

Could you guys check that you uploaded the proper version of bot files?

Note that I ran this command on my computer using Ubuntu 18.04 and java 13.0.7 version.

**Comment by Cheng-Xue** [comment]
Hi, please make sure that you include `1` after `java -jar data_lab_agent_v5.jar`
That number 1 controls how many agents will be running.
the commend should be `java -jar data_lab_agent_v5.jar 1`
please let us know if you still have issues.

**Comment by bic4907** [comment]
Solved!
It looks better to update `README.md` for not confusing.

Close issue.
