### ISSUE TITLE
Support other platform of ScienceBirds

### ISSUE THREAD

**Issue by bic4907** [phy-q/benchmark#2]
Hi,

I have a question for your test platform, the ScienceBirds game.
As I know, ScienceBirds supports other platforms like Windows and macOS, so I wonder is there any plan to distribute binaries for them.

Additionally, Is the game file in your repository a different version from [sciencebirdsframework](https://gitlab.com/aibirds/sciencebirdsframework/-/tree/master/ScienceBirds) or [ScienceBird github](https://github.com/lucasnfe/science-birds)?
I want to know how your version of game loads levels from my computer.

**Comment by Cheng-Xue** [comment]
Hi Bic,
We will try to release the version that supports windows and macOS as soon as we can.
For your 2nd question, the sciencebirdsframework is significantly different from the original sciencebird repo. You may put ur own game levels in the sciencebirdslevels/YOUR_OWN_FOLDER and change the path argument to YOUR_OWN_FOLDER when you are running the agents.
More detailed documentation will be included soon. Cheers.

**Comment by bic4907** [comment]
It sounds nice!

Your ScienceBird project is also an updated version from [sciencebirdsframework](https://gitlab.com/aibirds/sciencebirdsframework/-/tree/master), right?
As my institute, your ScienceBirds version read the levels in `sciencebirdslevels` directory that I unzipped.  
I will look forward to other platforms of yours :)

And, is there any plan of sharing your Unity project for customizing your ScienceBirds game?
Actually, I want to utilize it in the level generation task, so I have some plans to customize the game project.
It is because I have to log some game information (e.g., stable of structures, detailed results of game testing) dumping file.

Regards.

**Comment by RodgerLuo** [comment]
Hi,

Could you also provide a tentative timeline for releasing the macOS version? 

Thanks!

**Comment by Cheng-Xue** [comment]
ScienceBirds MacOS is released.

**Comment by bic4907** [comment]
Cheng-Xue,

Thank you for the quick updating!
I will try them and re-open this issue if there's any problem.

Close issue.
