### ISSUE TITLE
How can I run human experiments (i.e. render human modes) with your task scenarios?

### ISSUE THREAD

**Issue by hawe66** [phy-q/benchmark#5]
Hello, I'm trying to use your benchmark and downloaded `sciencebirdsgames/Linux.zip` to check whether human playing mode is available.  
It seems that `game_playing_interface.jar` is running server-side and `9001.x86_64` client-side, but I'm stuck on how to generate specific levels that I want to use in a human playing mode.  
And it seems that ml agent is generating it via calling `$(python Utils/GenerateTemplateName.py --level_path "fifth_generation")`.  
  
Can you give me an instruction on how to solve this?  
Also, I would be so glad if you can advise me on how to run the game on the website...  
I'm currently searching `aibrds.org` but I don't have a clear idea.

**Comment by Vimukthini** [comment]
Hi @hawe66 

We have added the game we used for human player data collection under the folder `humanplayerdatacollection`. It consists of all the game levels we used. The game levels are under `Science Birds Data > StreamingAssets > Levels`.

What do you mean by the game on the website? If it is about submitting an agent to the AIBIRDS competition, refer here: [http://aibirds.org/angry-birds-ai-competition.html]

**Comment by hawe66** [comment]
I want to conduct a human experiment (i.e. human players playing angry birds) with your scenarios (e.g. path clearing, etc.) by myself, not from your `humanplayerdatacollection`.  
But when I clicked `9001.x86_64`, angry bird playing interface was executed but with games presented were just random.  
So as you did in `sciencebirdsagnets` folder, I want to play angry birds with the proposed templates.  
  
And the game on the website is an extension of this. I want to conduct a human experiment online like Amazon MTurk,  
so I asked how to hold the game server online.  
It seems that similar stuff of mine is [Man vs. Machine Challenge](http://aibirds.org/man-vs-machine-challenge.html).

**Comment by XinrunXu** [comment]
Did you work out this issue?
